import {
  Home,
  Ship,
  Truck,
  Wallet,
  ShoppingCart,
  HandCoins,
  Calculator,
  Users,
  Building2,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Search,
  Plus,
  Download,
  Upload,
  X,
  Check,
  Trash2,
  Edit3,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  Calendar,
  Package,
  FileText,
  Receipt,
  StickyNote,
  Banknote,
  LogOut,
  Bell,
  Settings,
  Filter,
  TrendingUp,
  TrendingDown,
  AlertTriangle,
  CircleCheck,
  CircleAlert,
  Loader2,
  Inbox,
  Anchor,
  Container,
  Printer,
  ExternalLink,
  type LucideProps,
} from 'lucide-react';

const ICONS = {
  home: Home,
  ship: Ship,
  truck: Truck,
  wallet: Wallet,
  cart: ShoppingCart,
  coins: HandCoins,
  calculator: Calculator,
  users: Users,
  building: Building2,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  search: Search,
  plus: Plus,
  download: Download,
  upload: Upload,
  x: X,
  check: Check,
  trash: Trash2,
  edit: Edit3,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-right': ArrowDownRight,
  calendar: Calendar,
  package: Package,
  'file-text': FileText,
  receipt: Receipt,
  note: StickyNote,
  banknote: Banknote,
  logout: LogOut,
  bell: Bell,
  settings: Settings,
  filter: Filter,
  'trend-up': TrendingUp,
  'trend-down': TrendingDown,
  warning: AlertTriangle,
  'check-circle': CircleCheck,
  alert: CircleAlert,
  spinner: Loader2,
  inbox: Inbox,
  anchor: Anchor,
  container: Container,
  printer: Printer,
  'external-link': ExternalLink,
} as const;

export type IconName = keyof typeof ICONS;

type Props = LucideProps & { name: IconName };

export function Icon({ name, size = 16, ...rest }: Props) {
  const Cmp = ICONS[name];
  return <Cmp size={size} {...rest} />;
}
